module.exports = {
  "ALIVE_IMG": "https://telegra.ph/file/4b8107be4fdeaf42f3022.jpg"
  "PREFIX": ".",
  "AUTO_READ_STATUS": true,
  "MODE": "public",
  "BOT_NUMBER": "94741026371",
  "OMDB_API_KEY": "76cb7f39",
  "READ_CMD": true,
  "AUTO_VOICE": false,
  "AUTO_STICKER": false,
  "AUTO_REPLY": true,
  "AUTO_REACT": false,
  "WELCOME": false,
  "ANTI_BAD": false,
  "ANTI_BOT": true,
  "ANTI_LINK": true,
  "ALLWAYS_ONLINE": true,
  "MOROCCO_BLOCK": true,
  "BTN_MSG": false,
  "OWNER_NAME": "MR HASHAN",
  "NEWS_JID": "1234567890@s.whatsapp.net",
  "AUTO_TYPING": false,
  "AUTO_RECORDING": true,
  "AUTO_NEWS": false,
  "OWNER_REACT": false,
  "EMOJI": "💫"
};
